url: http://ibmstreams.github.io/sx43/
baseurl: /sx43
github_editme_path: IBMStreams/sx43/blob/gh-pages

# Site settings
title: IBM Streams
description: "IBM Streams Development Guides"

# Build settings
markdown: kramdown
permalink: pretty
detach:  false
port:    4000
host:    127.0.0.1
